#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 29, 2019 11:42:29 PM -04  platform: Windows NT

print('Cargando librerías...')
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from Multicolumn_Listbox import *

from pandas import read_excel
from datetime import datetime, date

excel_workbook  = '1.1. GyG Recibos.xlsm'
excel_worksheet = 'Vigilancia'

#
#   P R O C E S O
#

# Abre la hoja de cálculo de Recibos de Pago
print(f'Cargando hoja de cálculo "{excel_workbook}"...')

df = read_excel(excel_workbook, sheet_name=excel_worksheet)
df['Nro. Recibo'] = df['Nro. Recibo'].astype(int)
df = df[df['Fecha'] >= date(2019, 4, 1)]


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import genera_png
    genera_png.vp_start_gui()




